//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentMe.Utility.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentMe.Utility.Resource.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied..
        /// </summary>
        internal static string AuthAccessDenied {
            get {
                return ResourceManager.GetString("AuthAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username/password..
        /// </summary>
        internal static string AuthSignInInvalid {
            get {
                return ResourceManager.GetString("AuthSignInInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User signed in successfully..
        /// </summary>
        internal static string AuthSignInSuccess {
            get {
                return ResourceManager.GetString("AuthSignInSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User signed out successfully..
        /// </summary>
        internal static string AuthSignOutSuccess {
            get {
                return ResourceManager.GetString("AuthSignOutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists with {1} &quot;{2}&quot;..
        /// </summary>
        internal static string ErrorAlreadyExistsWith {
            get {
                return ResourceManager.GetString("ErrorAlreadyExistsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error..
        /// </summary>
        internal static string ErrorInternalServerError {
            get {
                return ResourceManager.GetString("ErrorInternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more required fields are missing or empty..
        /// </summary>
        internal static string ErrorMissingField {
            get {
                return ResourceManager.GetString("ErrorMissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not found..
        /// </summary>
        internal static string ErrorNotFound {
            get {
                return ResourceManager.GetString("ErrorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data retrieved successfully..
        /// </summary>
        internal static string ResponseRetrieveSuccess {
            get {
                return ResourceManager.GetString("ResponseRetrieveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} saved successfully..
        /// </summary>
        internal static string ResponseSaveSuccess {
            get {
                return ResourceManager.GetString("ResponseSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updated successfully..
        /// </summary>
        internal static string ResponseUpdateSuccess {
            get {
                return ResourceManager.GetString("ResponseUpdateSuccess", resourceCulture);
            }
        }
    }
}
